name: Daily-Data

on:
  schedule:
    - cron: '0 20-23,0-7 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Data Extraction and Export
      run: python Covid19_TH_dailyData.py
      
    - name: Thai Current Time
      uses: pluz85/thai-current-time@1.0
      id: thai-current-time

    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v4.1.2
      with:
        # Commit message
        commit_message: 🔥 ข้อมูลเมื่อ ⏱ ${{ steps.thai-current-time.outputs.thaiTime }}
        # Git branch name, where changes should be pushed too. Required if Action is used on the `pull_request` event
        branch: ${{ github.head_ref }}
        # Commit options (eg. --no-verify)
        commit_user_name: Schedule Bot 🤖
